apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello_world
    Hello: World
spec:
  containers:
  - name: hello
    image: busybox:1.28
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
  restartPolicy: OnFailure
    # The pod template ends here
